Pin setuptools < 45.0.0
Versions beginning with 45 removed the `Feature` module from setuptools,
but some older libraries we depend on in queens still depend on that
module.

  ImportError: cannot import name 'Feature